name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build the image
        run: ./build base-${{ matrix.arch }}
      - name: Upload debian ${{ matrix.arch }} image
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.arch }}
          path: .build/base-${{ matrix.arch }}*.raw
          retention-days: 2
